---
# Source: mlrun-ce/templates/pipelines/serviceaccounts/kubeflow-pipelines-container-builder.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
  labels:
    application-crd-id: kubeflow-pipelines
  name: kubeflow-pipelines-container-builder
