---
# Source: mlrun-ce/templates/pipelines/serviceaccounts/metadata-grpc-server.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
  labels:
    application-crd-id: kubeflow-pipelines
  name: metadata-grpc-server
