---
# Source: mlrun-ce/templates/pipelines/serviceaccounts/ml-pipeline-scheduledworkflow.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
  labels:
    application-crd-id: kubeflow-pipelines
  name: ml-pipeline-scheduledworkflow
