---
# Source: mlrun-ce/templates/pipelines/serviceaccounts/ml-pipeline-viewer-crd-service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
  labels:
    application-crd-id: kubeflow-pipelines
  name: ml-pipeline-viewer-crd-service-account
