---
# Source: mlrun-ce/templates/pipelines/serviceaccounts/pipeline-runner.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
  labels:
    application-crd-id: kubeflow-pipelines
  name: pipeline-runner
