---
# Source: mlrun-ce/templates/config/mlrun-pipelines-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mlrun-pipelines-config
data:
  MLRUN_KFP_URL: http://ml-pipeline.mlrun.svc.cluster.local:8888
