---
# Source: mlrun-ce/charts/spark-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-operator
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-delete-policy": hook-failed, before-hook-creation
    "helm.sh/hook-weight": "-10"
  labels:
    helm.sh/chart: spark-operator-1.1.25
    app.kubernetes.io/name: spark-operator
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v1beta2-1.3.7-3.1.1"
    app.kubernetes.io/managed-by: Helm
