---
# Source: mlrun-ce/charts/spark-operator/templates/spark-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-role
  namespace: default
  labels:
    helm.sh/chart: spark-operator-1.1.25
    app.kubernetes.io/name: spark-operator
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v1beta2-1.3.7-3.1.1"
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - "*"
---
# Source: mlrun-ce/charts/spark-operator/templates/spark-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark
  namespace: default
  labels:
    helm.sh/chart: spark-operator-1.1.25
    app.kubernetes.io/name: spark-operator
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v1beta2-1.3.7-3.1.1"
    app.kubernetes.io/managed-by: Helm
subjects:
- kind: ServiceAccount
  name: sparkapp
  namespace: default
roleRef:
  kind: Role
  name: spark-role
  apiGroup: rbac.authorization.k8s.io
