---
# Source: mlrun-ce/charts/spark-operator/templates/webhook-service.yaml
kind: Service
apiVersion: v1
metadata:
  name: spark-operator-webhook
  labels:
    helm.sh/chart: spark-operator-1.1.25
    app.kubernetes.io/name: spark-operator
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v1beta2-1.3.7-3.1.1"
    app.kubernetes.io/managed-by: Helm
spec:
  ports:
  - port: 443
    targetPort: 8080
    name: webhook
  selector:
    app.kubernetes.io/name: spark-operator
    app.kubernetes.io/instance: release-name
