---
# Source: mlrun-ce/charts/spark-operator/templates/webhook-cleanup-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: spark-operator-webhook-cleanup
  annotations:
    helm.sh/hook: pre-delete, pre-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  labels:
    helm.sh/chart: spark-operator-1.1.25
    app.kubernetes.io/name: spark-operator
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v1beta2-1.3.7-3.1.1"
    app.kubernetes.io/managed-by: Helm
spec:
  template:
    metadata:
      name: spark-operator-webhook-cleanup
    spec:
      serviceAccountName: spark-operator
      restartPolicy: OnFailure
      containers:
      - name: clean-secret
        image: ghcr.io/googlecloudplatform/spark-operator:v1beta2-1.3.7-3.1.1
        imagePullPolicy: IfNotPresent
        securityContext:
          {}
        command:
        - "/bin/sh"
        - "-c"
        - "curl -ik \
          -X DELETE \
          -H \"Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)\" \
          -H \"Accept: application/json\" \
          -H \"Content-Type: application/json\" \
          https://kubernetes.default.svc/api/v1/namespaces/default/secrets/spark-operator-webhook-certs \
          && \
          curl -ik \
          -X DELETE \
          -H \"Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)\" \
          -H \"Accept: application/json\" \
          -H \"Content-Type: application/json\" \
          --data \"{\\\"kind\\\":\\\"DeleteOptions\\\",\\\"apiVersion\\\":\\\"batch/v1\\\",\\\"propagationPolicy\\\":\\\"Foreground\\\"}\" \
          https://kubernetes.default.svc/apis/batch/v1/namespaces/default/jobs/spark-operator-webhook-init"
