---
# Source: mlrun-ce/charts/spark-operator/templates/webhook-init-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: spark-operator-webhook-init
  annotations:
    helm.sh/hook: pre-install, pre-upgrade
    helm.sh/hook-weight: "50"
  labels:
    helm.sh/chart: spark-operator-1.1.25
    app.kubernetes.io/name: spark-operator
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v1beta2-1.3.7-3.1.1"
    app.kubernetes.io/managed-by: Helm
spec:
  template:
    metadata:
      name: spark-operator-webhook-init
    spec:
      serviceAccountName: spark-operator
      restartPolicy: OnFailure
      containers:
      - name: main
        image: ghcr.io/googlecloudplatform/spark-operator:v1beta2-1.3.7-3.1.1
        imagePullPolicy: IfNotPresent
        securityContext:
          {}
        command: [
            "/usr/bin/gencerts.sh",
            "-n", "default",
            "-s", "spark-operator-webhook",
            "-r", "spark-operator-webhook-certs",
            "-p"
          ]
