---
# Source: mlrun-ce/templates/pipelines/secrets/mlpipeline-minio-artifact.yaml
apiVersion: v1
data:
  accesskey: "bWluaW8="
  secretkey: "bWluaW8xMjM="
kind: Secret
metadata:
  annotations:
  labels:
    application-crd-id: kubeflow-pipelines
  name: mlpipeline-minio-artifact
type: Opaque
