---
# Source: mlrun-ce/templates/pipelines/secrets/mysql-secret.yaml
apiVersion: v1
data:
  password: ""
  username: "cm9vdA=="
kind: Secret
metadata:
  annotations:
  labels:
    application-crd-id: kubeflow-pipelines
  name: mysql-secret
type: Opaque
