---
# Source: mlrun-ce/charts/kube-prometheus-stack/charts/prometheus-node-exporter/templates/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-exporter
  namespace: default
  labels:     
    helm.sh/chart: prometheus-node-exporter-4.4.2
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: prometheus-node-exporter
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/name: prometheus-node-exporter
    app.kubernetes.io/version: "1.3.1"
    jobLabel: node-exporter
    release: release-name
spec:
  jobLabel: jobLabel
  selector:
    matchLabels:
          
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/name: prometheus-node-exporter
  endpoints:
    - port: http-metrics
      scheme: http
