---
# Source: mlrun-ce/charts/mpi-operator/templates/mpi-operator-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mpi-operator
  namespace: default
  labels:
    app: mpi-operator
    chart: mpi-operator-0.6.0
    release: release-name
    heritage: Helm
