---
# Source: mlrun-ce/charts/mpi-operator/templates/mpijob-crd.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mpijobs.kubeflow.org
  labels:
    app: mpi-operator
    chart: mpi-operator-0.6.0
    release: release-name
    heritage: Helm
    component: crd
spec:
  group: kubeflow.org
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    plural: mpijobs
    singular: mpijob
    kind: MPIJob
    shortNames:
    - mj
    - mpij
