---
# Source: mlrun-ce/charts/minio/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: "default"
  labels:
    app: minio
    chart: minio-4.0.2
    release: release-name
    heritage: Helm
type: Opaque
data:
  rootUser: "bWluaW8="
  rootPassword: "bWluaW8xMjM="
