---
# Source: mlrun-ce/charts/minio/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: "default"
  labels:
    app: minio
    chart: minio-4.0.2
    release: release-name
    heritage: Helm
    monitoring: "true"
spec:
  type: NodePort
  ports:
    - name: http
      port: 9000
      protocol: TCP
      nodePort: 30080
  selector:
    app: minio
    release: release-name
