---
# Source: mlrun-ce/templates/jupyter-notebook/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mlrun-jupyter
  labels:
    helm.sh/chart: mlrun-ce-0.6.2
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mlrun-ce
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/component: "jupyter-notebook"
spec:
  type: NodePort
  ports:
    - name: http
      port: 8888
      protocol: TCP
      targetPort: http

      nodePort: 30040

  selector:
    app.kubernetes.io/name: mlrun-ce
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/component: "jupyter-notebook"
