---
# Source: mlrun-ce/charts/mlrun/templates/api-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mlrun-api
  labels:

    helm.sh/chart: mlrun-0.9.14
    app.kubernetes.io/version: "1.4.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mlrun
    app.kubernetes.io/instance: release-name
    release: release-name
    app.kubernetes.io/component: "api"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mlrun-api
subjects:
- kind: ServiceAccount
  name: mlrun-api
