---
# Source: mlrun-ce/charts/mlrun/templates/api-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mlrun-api
  labels:
    helm.sh/chart: mlrun-0.9.14
    app.kubernetes.io/version: "1.4.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mlrun
    app.kubernetes.io/instance: release-name
    release: release-name
    app.kubernetes.io/component: "api"
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http

      nodePort: 30070

  selector:
    app.kubernetes.io/name: mlrun
    app.kubernetes.io/instance: release-name
    release: release-name
    app.kubernetes.io/component: "api"
