---
# Source: mlrun-ce/charts/mlrun/templates/api-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlrun-api
  labels:

    helm.sh/chart: mlrun-0.9.14
    app.kubernetes.io/version: "1.4.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mlrun
    app.kubernetes.io/instance: release-name
    release: release-name
    app.kubernetes.io/component: "api"
