---
# Source: mlrun-ce/charts/mlrun/templates/db-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mlrun-db
  labels:
    helm.sh/chart: mlrun-0.9.14
    app.kubernetes.io/version: "1.4.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mlrun
    app.kubernetes.io/instance: release-name
    release: release-name
    app.kubernetes.io/component: "db"
data:

  health_check.sh: |
    mysql -u root -S /var/run/mysqld/mysql.sock -e 'SELECT 1'

  graceful_shutdown.sh: |
    mysql -u root -S /var/run/mysqld/mysql.sock -e 'SET GLOBAL innodb_fast_shutdown = 0; FLUSH TABLES WITH READ LOCK;'
    mysqladmin -u root -S /var/run/mysqld/mysql.sock shutdown

  init-v3io-mysql.sh: |
    #!/usr/bin/env bash
    set -e

    echo "Current user -> $(whoami)"
    LOCK_FILE=/var/lib/mysql/.init-complete
    if [ -f $LOCK_FILE ]
    then
      echo "MySQL has already been initialized. Skipping..."
    else
      echo "Initializing MySQL..."

      mysqld --initialize-insecure --user=999 --basedir=/usr --datadir=/tmp/mysql
      # and then copy the init files into real working directory (on Fuse mount)
      cp -R /tmp/mysql /var/lib/

      touch $LOCK_FILE
    fi

  v3io-mysql.sh: |
    #!/usr/bin/env bash
    set -e

    echo "Current user -> $(whoami)"

    MYSQL_SOCKET_FILE=/var/run/mysqld/mysql.sock
    INIT_SCRIPT="/etc/config/mysql/init-scripts/enable-root-remote-access.sql"

    echo "Starting MySQL ..."
    
    # TODO: review the innodb flags, they might not be needed anymore
    mysqld \
      --user=999 \
      --sql_mode="" \
      --init-file=$INIT_SCRIPT \
      --max-connections=512 \
      --innodb-adaptive-hash-index=0 \
      --innodb-read-io-threads=32 \
      --innodb-write-io-threads=32 \
      --innodb-purge-threads=16 \
      --innodb-buffer-pool-size=1073741824 \
      --innodb-buffer-pool-instances=8 \
      --innodb-page-cleaners=8 \
      --innodb-io-capacity=10000 \
      --innodb-flush-neighbors=0 \
      --socket=$MYSQL_SOCKET_FILE
