---
# Source: mlrun-ce/charts/mlrun/templates/mlrun-db-pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mlrun-db-pvc
  labels:
    helm.sh/chart: mlrun-0.9.14
    app.kubernetes.io/version: "1.4.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mlrun
    app.kubernetes.io/instance: release-name
    release: release-name
    app.kubernetes.io/component: "db"
  annotations:

    helm.sh/resource-policy: keep
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"
