---
# Source: mlrun-ce/charts/mlrun/templates/ui-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlrun-ui
  labels:
    helm.sh/chart: mlrun-0.9.14
    app.kubernetes.io/version: "1.4.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mlrun
    app.kubernetes.io/instance: release-name
    release: release-name
    app.kubernetes.io/component: "ui"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mlrun
      app.kubernetes.io/instance: release-name
      release: release-name
      app.kubernetes.io/component: "ui"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mlrun
        app.kubernetes.io/instance: release-name
        release: release-name
        app.kubernetes.io/component: "ui"
    spec:
      securityContext:
        {}
      containers:
        - name: mlrun-ui
          securityContext:
            {}
          image: 'mlrun/mlrun-ui:1.4.0'
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8090
              protocol: TCP
          env:
          - name: MLRUN_API_PROXY_URL
            value: 'http://mlrun-api.default.svc.cluster.local:8080'
          - name: MLRUN_NUCLIO_MODE
            value: enabled
          - name: MLRUN_NUCLIO_UI_URL
            value: http://localhost:30050
          - name: MLRUN_NUCLIO_API_URL
            value: http://nuclio-dashboard.default.svc.cluster.local:8070
          resources:
            {}
